In [1]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

/kaggle/input/rock-paper-scissors-landmarks/rps_landmarks.csv


# Random Forest Classifier
- Typical for classification problems like this

In [2]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
import numpy as np

df = pd.read_csv('/kaggle/input/rock-paper-scissors-landmarks/rps_landmarks.csv')

X = df.drop('label', axis=1).values #labels are our target
y = df['label'].values #.values converts to numpy array, which is what we expect for our input

#split 80/20 train/test
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

#initialize rfc model
model = RandomForestClassifier(
    n_estimators=100, 
    random_state=42, 
    n_jobs=-1,  #Use all available CPU cores
    max_depth=10 
)
model.fit(X_train, y_train)

RandomForestClassifier(max_depth=10, n_jobs=-1, random_state=42)

# Evaluate

In [3]:
y_pred = model.predict(X_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred, labels=model.classes_))

              precision    recall  f1-score   support

       paper       0.99      1.00      0.99       139
        rock       0.99      1.00      1.00       135
    scissors       1.00      0.98      0.99       134

    accuracy                           0.99       408
   macro avg       0.99      0.99      0.99       408
weighted avg       0.99      0.99      0.99       408

[[139   0   0]
 [  0 135   0]
 [  2   1 131]]


# Save Model

In [4]:
import pickle
import os

# Define the file path for the saved model
MODEL_FILENAME = 'rps_classifier_V1.pkl'

try:
    with open(MODEL_FILENAME, 'wb') as file:
        # Dump the trained model object into the file
        pickle.dump(model, file)
    print(f"Saved to {MODEL_FILENAME}")

except Exception as e:
    print(f"Error saving the model: {e}")

Saved to rps_classifier_V1.pkl


# Test saved model
- Using the hand_track.py script, you can grab landmarks of a photo and paste it in here to test the model

In [10]:
import pickle
import numpy as np
import pandas as pd

# Define the file path for the saved model
MODEL_FILENAME = '/kaggle/working/rps_classifier_V1.pkl'

sample = np.array([

[0.0, 0.0, 0.4073234242661263, 0.3783720444558931, 0.6523308663646984, 0.7593691127591208, 0.683455712796145, 1.2030607734448826, 0.46771554838487284, 1.3932555239997777, 0.26518619544265115, 1.0159355687581417, 0.2982084195848276, 1.3928644352211734, 0.3469741291045312, 1.1989850216282656, 0.3606316246331038, 1.0218857738116285, -0.07120835761167411, 0.9974614628176108, 0.017032609533326866, 1.3717514066130785, 0.08430276217154363, 1.2018386381707813, 0.08517636307959489, 1.0358279720874195, -0.3664375565008014, 0.9294348025420166, -0.23738567226549068, 1.2757658109277827, -0.17118390992698526, 1.1361932404583495, -0.162192437098848, 0.9687498633948916, -0.6034840289165444, 0.8224939165253495, -0.49353097685252206, 1.1333077767425672, -0.41014615454146536, 1.0278217025460648, -0.40189979574992496, 0.8765339023004185]
])
X_new = pd.DataFrame(sample) 

try:
    with open(MODEL_FILENAME, 'rb') as file:
        loaded_model = pickle.load(file)
        
    prediction = loaded_model.predict(X_new)
    
    print(f"Input Features Shape: {X_new.shape}")
    print(f"Predicted Gesture: {prediction[0].upper()}")

except FileNotFoundError:
    print(f"Error: Model file '{MODEL_FILENAME}' not found.")
except Exception as e:
    print(f"Error during prediction: {e}")

Input Features Shape: (1, 42)
Predicted Gesture: ROCK


In [6]:
!pip show scikit-learn

Name: scikit-learn
Version: 1.2.2
Summary: A set of python modules for machine learning and data mining
Home-page: http://scikit-learn.org
Author: 
Author-email: 
License: new BSD
Location: /usr/local/lib/python3.11/dist-packages
Requires: joblib, numpy, scipy, threadpoolctl
Required-by: bayesian-optimization, Boruta, category_encoders, cesium, eli5, fastai, hdbscan, hep_ml, imbalanced-learn, librosa, lime, mlxtend, nilearn, pyLDAvis, pynndescent, rgf-python, scikit-learn-intelex, scikit-optimize, scikit-plot, sentence-transformers, shap, sklearn-compat, sklearn-pandas, TPOT, tsfresh, umap-learn, woodwork, yellowbrick
